### ISSUE TITLE
Binary mongodump not found

### ISSUE THREAD

**Issue by olawalejuwonm** [boly38/node-mongotools#78]
I have been searching for a library as this, my thought was that the library is bundled with mongodump and mongorestore. I get the error message 'Binary mongodump not found' when trying to use it

**Comment by boly38** [comment]
Hi @olawalejuwonm 

First you need to have mongodb database tools installed

For example following this guide
https://www.mongodb.com/docs/database-tools/installation/installation/

Second you should verify that from command line you re able to "see" that binary (update your PATH value if required with `xx/bin/` directory location of this tools)

For Linux like command that should fix

For Windows command you could - since today version v2
2.1 - setup binary env var to setup binary name 
Ex. 

set MT_MONGODUMP=mongodump.exe

And

set MT_MONGORESTORE=mongorestore.exe

Let me know if this answer helps you
Regards

**Comment by olawalejuwonm** [comment]
I want to run this on cloud severs like heroku, ec2 and many others.

So I need the binary to be present when I install this library

**Comment by boly38** [comment]
Yes they must be present.
You need to first follow for example classic ubuntu install
(For heroku I m not sure if there is a way to get this tools as mongodb feature is giving you only mongo connectivity ...)

For example for github actions context this project will detup this tools using apt (cf shell code) :
https://github.com/boly38/action-mongo-tools

**Comment by olawalejuwonm** [comment]
Wow please I'll like to learn more about the github action.  Can I schedule database backup with it?

**Comment by boly38** [comment]
This project uses this github actions in order to setup mongodump binary
https://github.com/boly38/node-mongotools/blob/main/.github/workflows/main.yml#L49

So yes on your own project you could customize your own step witth this tools plus this wrapper to dump (even on dropbox)

One condition is that your database may be accessible from githubaction context (ex you peovide mongo uri with secret as github action secret frombyour project settings

**Comment by olawalejuwonm** [comment]
Please 🙏 can you help with sample code that use github secret and back up
to Dropbox.

I'll figure out the cron job

**Comment by boly38** [comment]
In order to design a dedicated github actions:
- variables to set are well-described in root readme of the project, simply pass them as action secret
- stage example: as pointed below, current project tests are launched from github action and are already doing dump (with backup when you have a dropbox token set)

for the rest, you may do your own nodejs class or mt use to customize your mongodump. 
This is specific to your needs.

Basic example of what I say using project class:
````
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json

    - name: Install dependencies
      # npx force-resolutions : in case of Permission denied: run it locally to fix package-lock.json
      run: |
        echo "install"
        npm run preinstall
        npm install
        echo "show outdated (if any)"
        npm outdated --depth=3 || echo "you must think about update your dependencies :)"

    - name: doing my dump
      env:
        MT_MONGO_URI: ${{ secrets.MT_MONGO_URI}}
        MT_PATH: ${{ secrets.MT_PATH}}
      run: node mt dump
````

(note that dropbox long-lived access-token has changed : #79 and I planned to work on it soon)
